theme = "catppuccin_macchiato"

#theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
rulers = [80]
shell = ["zsh", "-c"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"ret" = ["insert_newline", "insert_mode"]
"backspace" = ["delete_selection", "move_line_up"]


[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
[editor.soft-wrap]
enable = true
